version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 3s
      retries: 10

  adminer:
    image: adminer:latest
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    environment:
      # ensure DATABASE_URL points to db service host, not localhost
      DATABASE_URL: "postgresql://app:app@db:5432/appdb?schema=public"
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-15m}
      NODE_ENV: development
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata: